### ISSUE TITLE
[Suggestion] Free-text attribution field when submitting scene

### ISSUE THREAD

**Issue by BadIdeasBureau** [SvenWerlen/moulinette-scenes#1]
Various patreon artists allow free use of their mapmaking assets, with attribution (e.g. Forgotten Adventures).  If I'm making my own map with their assets, there currently isn't a way to provide this attribution within the module.

A free-text field which allows the uploader to enter whatever they want as attribution (e.g. if they need to credit half a dozen artists, cite the WoTC fan content policy, etc) would allow space for as much attribution as is needed to share the scenes with correct licensing for all assets used.

**Comment by SvenWerlen** [comment]
This is a very good point and suggestion. Since the approval process is still manual, if you want to contribute, you can submit a scene without this information and I'll contact you anyway to get more details. I'll work on this later next month, working on cloud capabilities for the time-being.

**Comment by SvenWerlen** [comment]
Moulinette evolved a lot since April. Submitting a scene is not possible any more because it's very time consuming for me to review them. Any creator can easily manage their own scenes on Moulinette Cloud. I'm going to close this suggestion for that reason.
