### ISSUE TITLE
Unknow creator for major artist

### ISSUE THREAD

**Issue by davelacorneille** [SvenWerlen/moulinette-scenes#8]
Do you think it's related to moulinette or the artist not doing something with their module?

![20230803122251](https://github.com/SvenWerlen/moulinette-scenes/assets/99104959/3ae6927c-c511-4435-bfa8-e107ae0953be)

![image](https://github.com/SvenWerlen/moulinette-scenes/assets/99104959/f1b1f07a-0a46-48de-b4fb-2b06d41f3e45)

Thank you!

**Comment by SvenWerlen** [comment]
This is fixed in `v-11.1.5`. It was due to a change in V11 (authors is now a list)
